### ISSUE TITLE
Get ML Pipeline running on NPU

### ISSUE THREAD

**Issue by sah4jpatel** [BUZZ-Blimps/CatchingBlimp#28]
Working with rknn-toolkit2 to deploy a vision model on NPU

**Comment by sah4jpatel** [comment]
any updates too add here? @Rhyme0730

**Comment by Rhyme0730** [comment]
I directly converted our previous model best.pt --> best.onnx --> best.rknn. And then implementing it on npu but failed. Now trying to train a new test yolo model on npu.

**Comment by sah4jpatel** [comment]
Are you using the docker instance to run the rknn-toolkit2 converter? I was having trouble with that too with OP set incompatibility reasons. I'll be spending tonight on figuring out how to convert huggingface onnx models to rknn.

**Comment by Rhyme0730** [comment]
No, I don't use docker. Instead, for converting model, I just install rknn-toolkit2 on PC and convert .onnx model to .rknn. Then use ssh scp -r command copy them to orangepi and run it on rknn-toolkit-lite2.
The entire work flow is: Converting model on PC --> ssh scp to Opi --> Using rknn-toolkit-lite2 running model on Opi

**Comment by sah4jpatel** [comment]
I see. Let me know if you solve that issue you ran into.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Rhyme0730** [comment]
Trying to:
1. Training custom yolov5 model (Finish)
2. Convert yolov5.pt into yolov5.onnx (Finish)
3. Conver yolov5.onnx into yolov5.rknn (Official code not work, TBD)
4. Implement yolov5.rknn on board using rknn-toolkit-lite2 (match input output size, TBD)

**Comment by Rhyme0730** [comment]
@sah4jpatel Do you know how to convert .onnx to .rknn model for a custom yolo model? I am currently stuck in it.

**Comment by sah4jpatel** [comment]
I haven't tried that yet. I am about to start investigating that. I opted to use the dockerized version of RKNN-toolkit on Ubuntu20.04 because it seems like the best experience to get everything working. However, I was getting an error with incompatible OP sets but that's because I was trying to convert Florence2's weights (which might be too new or just incompatible). I found v10 onnx weights on huggingface that I downloaded, I'll try debugging diligently tonight.

**Comment by Rhyme0730** [comment]
Ok, I see. The compability is an esstential part for us, we can document every tool's version after running successfully.

**Comment by sah4jpatel** [comment]
Yea I think that will be important. V10 had so many issues, V8 was almost flawless once I wrote the script to convert it.

**Comment by sah4jpatel** [comment]
we have V5 working, will test V8 and V10 this week for next milestone.

**Comment by sah4jpatel** [comment]
YOLOv10 still largely undocumented, and the outputs don't match that which is expected on RKNN. Shifting focus to trying to get YOLOv10 running off the Coral TPU to see if that can work as a viable solution.
