### ISSUE TITLE
NEW DESIGNS

### ISSUE THREAD

**Issue by Retartsi** [BUZZ-Blimps/CatchingBlimp#33]
WE NEED NEW DESIGN IDEA!!!

**Comment by sah4jpatel** [comment]
😭😭, is there context to this

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Dayong Liu ***@***.***>
Sent: Thursday, June 27, 2024 1:31:23 PM
To: SWAMP-Blimps/CatchingBlimp ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [SWAMP-Blimps/CatchingBlimp] NEW DESIGNS (Issue #33)


WE NEED NEW DESIGN IDEA!!!

**Comment by Retartsi** [comment]
We need to design a new basket and gate system that fit on our new design. 
We might also need to redesign the entire blimp (that includes design new parts, redesign old parts, or maybe design a completely new blimp from zero) BRAINSTORMING ANY IDEAS!!!

**Comment by sah4jpatel** [comment]
Would you be able to come up with a minimum list of requirements that a redesign would have, like the constraints, what we want to avoid, etc?

Putting it to words, may help start the brainstorming process

**Comment by Retartsi** [comment]
I don't want to put many constraints for brainstorming, I want all kinds of crazy ideas. The only constraints are probably coming from the competition rules, like lighter than air, the balloon itself can only be red/blue, and no green or purple (and maybe no yellow and orange) color on the blimp, etc.

**Comment by J4mZzy** [comment]
Please contribute your ideas here
