### ISSUE TITLE
Rossify yolov5+rknn msgs

### ISSUE THREAD

**Issue by Rhyme0730** [BUZZ-Blimps/CatchingBlimp#38]

**Comment by Rhyme0730** [comment]
![image](https://github.com/user-attachments/assets/140078b1-2e1e-4fac-8995-4e77e079ae10)

**Comment by Rhyme0730** [comment]
Tried reinstalling rknn-toolkit-lite2 new version.
There is problem with input reference image dimension, using `img=np.expand_dims(img, axis=0)` can solve this issue.
But it seems our multi-threading code only works on old rknn-toolkit-lite2 version.

**Comment by Rhyme0730** [comment]
Can not run ros on python 3.9, it should come with the right ubuntu 22.04 default python 3.10. So we need to move the entire rknn and other package into python 3.10 and rewrite the script.

**Comment by Rhyme0730** [comment]
Issue solved, find a rknn-toolkit2-lite 1.5.2 version installation package for python3.10 [here](https://github.com/rockchip-linux/rknn-toolkit2/blob/b7c3b5c3c6b2836fe98569bd2013d01ab614f055/rknn_toolkit_lite2/packages/rknn_toolkit_lite2-1.5.2-cp310-cp310-linux_aarch64.whl). Now there is no conflict with ros2 and rknn toolkit lite2. Also notice we don't use conda environment anymore since it has conflicts with ros2 humble.

**Comment by sah4jpatel** [comment]
Any updates to this @Rhyme0730
